"""
NSE-500 Stock Symbols

Top 500 stocks on NSE by market cap (representative sample for scanning).
Format: "SYMBOL.NS" for yfinance compatibility

Note: This is a curated list of liquid, tradeable stocks.
Update quarterly to reflect index changes.

Last Updated: November 2025
"""

NSE_500_SYMBOLS = [
    # Nifty 50 (Large Cap)
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "TITAN.NS",
    "SUNPHARMA.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "BAJFINANCE.NS", "HCLTECH.NS",
    "WIPRO.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "TATASTEEL.NS",
    "M&M.NS", "ADANIPORTS.NS", "JSWSTEEL.NS", "HINDALCO.NS", "INDUSINDBK.NS",
    "COALINDIA.NS", "TECHM.NS", "GRASIM.NS", "CIPLA.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "HEROMOTOCO.NS", "SBILIFE.NS", "BAJAJFINSV.NS", "BRITANNIA.NS",
    "DIVISLAB.NS", "BPCL.NS", "TATACONSUM.NS", "APOLLOHOSP.NS", "HDFCLIFE.NS",
    "UPL.NS", "TATAMOTORS.NS", "ADANIENT.NS", "BAJAJ-AUTO.NS", "SHREECEM.NS",

    # Next 50 (Large/Mid Cap)
    "HAVELLS.NS", "DABUR.NS", "PIDILITIND.NS", "GODREJCP.NS", "MARICO.NS",
    "COLPAL.NS", "SIEMENS.NS", "ABB.NS", "BOSCHLTD.NS", "BERGEPAINT.NS",
    "MOTHERSON.NS", "GAIL.NS", "PAGEIND.NS", "AMBUJACEM.NS", "ACC.NS",
    "INDIGO.NS", "BANDHANBNK.NS", "MUTHOOTFIN.NS", "TORNTPHARM.NS", "BIOCON.NS",
    "LUPIN.NS", "DMART.NS", "NAUKRI.NS", "ZOMATO.NS", "PAYTM.NS",
    "PIIND.NS", "SBICARD.NS", "ICICIPRULI.NS", "MCDOWELL-N.NS", "AUROPHARMA.NS",
    "ALKEM.NS", "ZYDUSLIFE.NS", "INDUSTOWER.NS", "TATAPOWER.NS", "PFC.NS",
    "RECLTD.NS", "IRCTC.NS", "HAL.NS", "BEL.NS", "SAIL.NS",
    "VEDL.NS", "NMDC.NS", "BHEL.NS", "CANBK.NS", "BANKBARODA.NS",
    "PNB.NS", "UNIONBANK.NS", "IOC.NS", "HINDPETRO.NS", "MGL.NS",

    # Mid Cap 100 (Selected liquid stocks)
    "TRENT.NS", "LICI.NS", "ADANIPOWER.NS", "ADANIGREEN.NS", "JIOFIN.NS",
    "BAJAJHLDNG.NS", "DLF.NS", "GODREJPROP.NS", "PRESTIGE.NS", "OBEROIRLTY.NS",
    "PHOENIXLTD.NS", "IGL.NS", "PETRONET.NS", "GUJGASLTD.NS", "ATGL.NS",
    "CONCOR.NS", "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS",
    "OFSS.NS", "L&TFH.NS", "CHOLAFIN.NS", "LICHSGFIN.NS", "SHRIRAMFIN.NS",
    "TATACOMM.NS", "ASTRAL.NS", "POLYCAB.NS", "KEI.NS", "CROMPTON.NS",
    "VOLTAS.NS", "BLUESTARCO.NS", "DIXON.NS", "AMBER.NS", "WHIRLPOOL.NS",
    "VBL.NS", "TATAELXSI.NS", "BALKRISIND.NS", "MRF.NS", "CEAT.NS",
    "APOLLOTYRE.NS", "ATUL.NS", "SRF.NS", "DEEPAKNTR.NS", "GNFC.NS",
    "CHAMBLFERT.NS", "COROMANDEL.NS", "RALLIS.NS", "UPL.NS", "AAVAS.NS",

    # IT & Software
    "TECHM.NS", "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS",
    "MINDTREE.NS", "OFSS.NS", "ROUTE.NS", "ZENTEC.NS", "DATAPATTNS.NS",
    "FSL.NS", "HAPPSTMNDS.NS", "RATEGAIN.NS", "TANLA.NS", "MASTEK.NS",

    # Pharma & Healthcare
    "SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "BIOCON.NS",
    "LUPIN.NS", "TORNTPHARM.NS", "AUROPHARMA.NS", "ALKEM.NS", "ZYDUSLIFE.NS",
    "APOLLOHOSP.NS", "MAXHEALTH.NS", "FORTIS.NS", "NARAYANANHEALTH.NS", "LAURUSLABS.NS",
    "GRANULES.NS", "NATCOPHARM.NS", "SYNGENE.NS", "THYROCARE.NS", "METROPOLIS.NS",

    # FMCG & Consumer
    "HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "TATACONSUM.NS",
    "DABUR.NS", "GODREJCP.NS", "MARICO.NS", "COLPAL.NS", "EMAMILTD.NS",
    "VBL.NS", "TATACONSUM.NS", "VARUN.NS", "RADICO.NS", "ZOMATO.NS",

    # Auto & Auto Components
    "MARUTI.NS", "TATAMOTORS.NS", "M&M.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS",
    "HEROMOTOCO.NS", "MOTHERSON.NS", "BOSCHLTD.NS", "EXIDEIND.NS", "MRF.NS",
    "APOLLOTYRE.NS", "CEAT.NS", "BALKRISIND.NS", "TVSMOTORS.NS", "ESCORTS.NS",
    "ASHOKLEY.NS", "BHARATFORG.NS", "ENDURANCE.NS", "SUPRAJIT.NS", "SONA.NS",

    # Banking & Financial Services
    "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS", "KOTAKBANK.NS",
    "INDUSINDBK.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "CHOLAFIN.NS", "SHRIRAMFIN.NS",
    "MUTHOOTFIN.NS", "LICH SGFIN.NS", "L&TFH.NS", "PNBHOUSING.NS", "CANBK.NS",
    "BANKBARODA.NS", "PNB.NS", "UNIONBANK.NS", "IDFCFIRSTB.NS", "FEDERALBNK.NS",

    # Cement
    "ULTRACEMCO.NS", "AMBUJACEM.NS", "ACC.NS", "SHREECEM.NS", "DALMIACEM.NS",
    "RAMCOCEM.NS", "JKCEMENT.NS", "HEIDELBERG.NS", "INDIACEM.NS", "BIRLACORPN.NS",

    # Metals & Mining
    "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS", "JINDALSTEL.NS",
    "SAIL.NS", "NMDC.NS", "COALINDIA.NS", "MOIL.NS", "WELCORP.NS",
    "HINDZINC.NS", "NATIONALUM.NS", "APL.NS", "RATNAMANI.NS", "KAJARIACER.NS",

    # Energy & Power
    "RELIANCE.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "BPCL.NS",
    "IOC.NS", "HINDPETRO.NS", "GAIL.NS", "TATAPOWER.NS", "ADANIPOWER.NS",
    "ADANIGREEN.NS", "TORNTPOWER.NS", "JSPL.NS", "ADANITRANS.NS", "PFC.NS",
    "RECLTD.NS", "IEX.NS", "CESC.NS", "NHPC.NS", "SJVN.NS",

    # Telecom
    "BHARTIARTL.NS", "TATACOMM.NS", "INDUSTOWER.NS", "GTPL.NS", "ROUTE.NS",

    # Real Estate
    "DLF.NS", "GODREJPROP.NS", "PRESTIGE.NS", "OBEROIRLTY.NS", "PHOENIXLTD.NS",
    "BRIGADE.NS", "SOBHA.NS", "IBREALEST.NS", "MAHLIFE.NS", "SUNTECK.NS",

    # Retail & E-commerce
    "DMART.NS", "TRENT.NS", "SHOPERSTOP.NS", "ABFRL.NS", "TITAN.NS",
    "ZOMATO.NS", "NYKAA.NS", "PVR.NS", "RELAXO.NS", "BATA.NS",

    # Infrastructure & Capital Goods
    "LT.NS", "ADANIPORTS.NS", "HAL.NS", "BEL.NS", "ABB.NS",
    "SIEMENS.NS", "THERMAX.NS", "CARBORUNIV.NS", "GRINDWELL.NS", "SCHAEFFLER.NS",
    "CUMMINSIND.NS", "CROMPTON.NS", "HAVELLS.NS", "POLYCAB.NS", "KEI.NS",

    # Chemicals
    "PIDILITIND.NS", "ATUL.NS", "SRF.NS", "DEEPAKNTR.NS", "GNFC.NS",
    "CHAMBLFERT.NS", "COROMANDEL.NS", "BALRAMCHIN.NS", "TATACHEM.NS", "AARTI.NS",
    "NAVINFLUOR.NS", "CHEMFAB.NS", "CLEAN.NS", "ALKYLAMINE.NS", "FINEORG.NS",

    # Hotels & Tourism
    "INDHOTEL.NS", "LEMONTREE.NS", "CHALET.NS", "EIH.NS", "MAHINDHOLIDAYS.NS",
]

def get_nse_500_symbols():
    """Get list of NSE-500 symbols in yfinance format"""
    return NSE_500_SYMBOLS

def get_nifty_50_symbols():
    """Get just Nifty 50 symbols"""
    return NSE_500_SYMBOLS[:50]

def get_nifty_next_50_symbols():
    """Get Nifty Next 50 symbols"""
    return NSE_500_SYMBOLS[50:100]

if __name__ == "__main__":
    print(f"Total NSE symbols: {len(NSE_500_SYMBOLS)}")
    print(f"Nifty 50: {len(get_nifty_50_symbols())}")
    print(f"Nifty Next 50: {len(get_nifty_next_50_symbols())}")
